version: '3'

services:
  postgres-compose:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "123456789"
    volumes:
      - ./PostgreSQL/data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "jhonleandres.silva@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "12345678"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
